version: "3.8"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://gr8gsgrw-5000.euw.devtunnels.ms}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-https://gr8gsgrw-5000.euw.devtunnels.ms}
    restart: unless-stopped
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge
